export const AdminCallbacks = {
    MainMenu: 'm',

    Schedule: 's',
    ActiveTrainings: 'tr:a',
    ArchivedTrainings: 'tr:r',
    ArchivedTrainingPrefix: 'tr:ra:',
    ArchiveMonthPrefix: 'tr:rm:',
    ArchiveSearch: 'tr:rs',

    Players: 'p',
    Settings: 'cfg',
    Chats: 'c',

    AddChat: 'c:a',
    ConfirmAddChat: 'c:ac',

    CreateTemplate: 't:c',
    ConfirmCreateTemplate: 't:cc',
    CancelCreateTemplate: 't:cx',

    ConfirmEditTemplate: 't:ec',
    CancelEditTemplate: 't:ex',

    TemplatePrefix: 't:v:',
    TemplateEditPrefix: 't:e:',
    TemplateTogglePrefix: 't:g:',
    TemplateDeletePrefix: 't:d:',
    TemplateDeleteConfirmPrefix: 't:x:',

    TemplateChatPrefix: 'tc:',
    SelectTemplateChat: 'tc:s',
    BackFromTemplateChat: 'tc:b',
    BackFromTemplatePreview: 'tp:b',

    UnconfirmedPlayers: 'p:u',
    AllPlayers: 'p:a',
    KnownPlayers: 'p:k',
    InactivePlayers: 'p:i',
    PlayerShowFirst: 'p:f',
    PlayerBrowseNext: 'p:bn',
    PlayerBrowsePrevious: 'p:bp',
    PlayerNewSearch: 'p:us',
    PlayerNewConfirm: 'p:uc',
    PlayerNewEdit: 'p:ue',
    PlayerNewMerge: 'p:um',
    PlayerIncludeInactive: 'p:ii',
    PlayerCreateAnyway: 'p:ca',
    PlayerRenameAnyway: 'p:ra',

    CreatePlayer: 'p:c',
    ConfirmCreatePlayer: 'p:cc',
    SearchPlayers: 'p:s',

    PlayerPrefix: 'p:v:',
    PlayerConfirmPrefix: 'p:cf:',
    PlayerUnconfirmPrefix: 'p:cu:',
    PlayerAliasPrefix: 'p:al:',
    PlayerTogglePrefix: 'p:t:',
    PlayerDeletePrefix: 'p:d:',
    PlayerDeleteConfirmPrefix: 'p:dx:',
    PlayerMergePrefix: 'p:m:',
    PlayerMergeTargetPrefix: 'p:mt:',
    PlayerMergeConfirmPrefix: 'p:mc:',
    PlayerAddTrainingPrefix: 'p:at:',
    PlayerRemoveTrainingPrefix: 'p:rt:',
    PlayerSelectAddTrainingPrefix: 'p:sat:',
    PlayerSelectRemoveTrainingPrefix: 'p:srt:',

    TrainingPrefix: 'tr:v:',
    TrainingClosePrefix: 'tr:c:',
    TrainingOpenPrefix: 'tr:o:',
    TrainingCancelPrefix: 'tr:x:',
    TrainingCancelConfirmPrefix: 'tr:xc:',
    TrainingRefreshPrefix: 'tr:r:',
    TrainingFinishPrefix: 'tr:f:',
    TrainingParticipantsPrefix: 'tr:p:',

    TrainingAddPlayerPrefix: 'tr:ap:',
    TrainingRemovePlayerPrefix: 'tr:rp:',
    TrainingSelectAddPlayerPrefix: 'tr:sap:',
    TrainingSelectRemovePlayerPrefix: 'tr:srp:',

    ChatPrefix: 'c:v:',
    ChatTogglePrefix: 'c:t:',
    ChatDeletePrefix: 'c:d:',
    ChatDeleteConfirmPrefix: 'c:x:',

    SettingsToggleCleanChat: 'cfg:tc',
    SettingsEditPrefix: 'cfg:e:',
    SettingsAdmins: 'cfg:a',
    SettingsAddAdmin: 'cfg:aa',
    SettingsRemoveAdminPrefix: 'cfg:ar:',
    SettingsStatus: 'cfg:st',

    Help: 'h',
} as const;
