export const AdminCallbacks = {
    MainMenu: 'm',
    Back: 'nav:back',

    Schedule: 's',
    ScheduleExceptions: 'ex',
    ScheduleExceptionAdd: 'ex:add',
    ScheduleExceptionHistory: 'ex:hist',
    ScheduleExceptionExtra: 'ex:extra',
    ScheduleExceptionEntryPrefix: 'ex:e:',
    ScheduleExceptionViewPrefix: 'ex:v:',
    ScheduleExceptionActionPrefix: 'ex:a:',
    ScheduleExceptionConfirm: 'ex:ok',
    ScheduleExceptionDelete: 'ex:del',
    ScheduleExceptionDeleteConfirm: 'ex:delok',
    ScheduleExceptionRevertConfirm: 'ex:revert',
    ScheduleExceptionChatPrefix: 'ex:c:',
    ScheduleUpcoming: 'ex:next',
    ActiveTrainings: 'tr:a',
    ArchivedTrainings: 'tr:r',
    ArchivedTrainingPrefix: 'tr:ra:',
    ArchiveMonthPrefix: 'tr:rm:',
    ArchiveSearch: 'tr:rs',
    TrainingWeek: 'tr:w',
    TrainingWeekPrefix: 'tr:w:',
    TrainingSearch: 'tr:s',
    TrainingCreate: 'tr:n',
    TrainingCreatePublishNow: 'tr:n:now',
    TrainingCreateDraft: 'tr:n:draft',
    TrainingCreateSchedule: 'tr:n:schedule',
    TrainingEditPrefix: 'tr:e:',
    TrainingEditFieldPrefix: 'tr:ef:',
    TrainingEditConfirm: 'tr:e:ok',

    Players: 'p',
    Settings: 'cfg',
    Chats: 'c',
    Setup: 'setup',
    SetupContinue: 'setup:go',
    SetupChat: 'setup:c',
    SetupSchedule: 'setup:s',
    SetupSkip: 'setup:skip',
    Readiness: 'cfg:ready',

    AddChat: 'c:a',
    ConfirmAddChat: 'c:ac',

    CreateTemplate: 't:c',
    ConfirmCreateTemplate: 't:cc',
    CancelCreateTemplate: 't:cx',

    ConfirmEditTemplate: 't:ec',
    CancelEditTemplate: 't:ex',

    TemplatePrefix: 't:v:',
    TemplateEditPrefix: 't:e:',
    TemplateTogglePrefix: 't:g:',
    TemplateDeletePrefix: 't:d:',
    TemplateDeleteConfirmPrefix: 't:x:',
    TemplateDeleteWithExceptionsPrefix: 't:xa:',

    TemplateChatPrefix: 'tc:',
    SelectTemplateChat: 'tc:s',
    BackFromTemplateChat: 'tc:b',
    BackFromTemplatePreview: 'tp:b',

    UnconfirmedPlayers: 'p:u',
    AllPlayers: 'p:a',
    KnownPlayers: 'p:k',
    InactivePlayers: 'p:i',
    PlayerShowFirst: 'p:f',
    PlayerBrowseNext: 'p:bn',
    PlayerBrowsePrevious: 'p:bp',
    PlayerNewSearch: 'p:us',
    PlayerNewConfirm: 'p:uc',
    PlayerNewEdit: 'p:ue',
    PlayerNewMerge: 'p:um',
    PlayerIncludeInactive: 'p:ii',
    PlayerCreateAnyway: 'p:ca',
    PlayerRenameAnyway: 'p:ra',
    PlayerImport: 'pi',
    PlayerImportTemplate: 'pi:t',
    PlayerImportFormat: 'pi:f',
    PlayerImportConfirm: 'pi:ok',
    PlayerImportSkipConflicts: 'pi:skip',
    PlayerImportCancel: 'pi:x',
    PlayerExport: 'pe',
    PlayerExportCsv: 'pe:c',
    PlayerExportJson: 'pe:j',
    PlayerDuplicates: 'pd',
    PlayerTelegramImport: 'pt',
    PlayerTelegramConnect: 'pt:c',
    PlayerTelegramQrRefreshPrefix: 'tqr:r:',
    PlayerTelegramQrCancelPrefix: 'tqr:c:',
    PlayerTelegramConnection: 'pt:cfg',
    PlayerTelegramValidate: 'pt:val',
    PlayerTelegramDisconnect: 'pt:disc',
    PlayerTelegramDisconnectConfirm: 'pt:disc:ok',
    PlayerTelegramAddSource: 'pt:add',
    PlayerTelegramSourcePrefix: 'pt:s:',
    PlayerTelegramImportConfirmPrefix: 'pt:ok:',
    PlayerTelegramReviewPrefix: 'pt:rv:',
    PlayerTelegramSkipBlockedPrefix: 'pt:sk:',
    PlayerTelegramAmbiguousMergePrefix: 'tir:m:',
    PlayerTelegramAmbiguousCreatePrefix: 'tir:n:',
    PlayerTelegramAmbiguousSkipPrefix: 'tir:s:',
    PlayerTelegramImportCancelPrefix: 'pt:x:',

    CreatePlayer: 'p:c',
    ConfirmCreatePlayer: 'p:cc',
    SearchPlayers: 'p:s',

    PlayerPrefix: 'p:v:',
    PlayerConfirmPrefix: 'p:cf:',
    PlayerUnconfirmPrefix: 'p:cu:',
    PlayerAliasPrefix: 'p:al:',
    PlayerTogglePrefix: 'p:t:',
    PlayerDeletePrefix: 'p:d:',
    PlayerDeleteConfirmPrefix: 'p:dx:',
    PlayerMergePrefix: 'p:m:',
    PlayerMergeTargetPrefix: 'p:mt:',
    PlayerMergeConfirmPrefix: 'p:mc:',
    PlayerAddTrainingPrefix: 'p:at:',
    PlayerRemoveTrainingPrefix: 'p:rt:',
    PlayerSelectAddTrainingPrefix: 'p:sat:',
    PlayerSelectRemoveTrainingPrefix: 'p:srt:',

    TrainingPrefix: 'tr:v:',
    TrainingClosePrefix: 'tr:c:',
    TrainingOpenPrefix: 'tr:o:',
    TrainingCancelPrefix: 'tr:x:',
    TrainingCancelConfirmPrefix: 'tr:xc:',
    TrainingRefreshPrefix: 'tr:r:',
    TrainingRepublishPrefix: 'tr:pub:',
    TrainingFinishPrefix: 'tr:f:',
    TrainingParticipantsPrefix: 'tr:p:',

    TrainingAddPlayerPrefix: 'tr:ap:',
    TrainingRemovePlayerPrefix: 'tr:rp:',
    TrainingSelectAddPlayerPrefix: 'tr:sap:',
    TrainingSelectRemovePlayerPrefix: 'tr:srp:',
    TrainingRemovePlacesPrefix: 'tr:rmv:',
    TrainingNewPlayerPreview: 'tr:np',
    TrainingNewPlayerEdit: 'tr:ne',
    TrainingNewPlayerSearchAgain: 'tr:ns',
    TrainingNewPlayerPlaces: 'tr:ng',
    TrainingNewPlayerConfirm: 'tr:nc',
    TrainingNewPlayerCreateAnyway: 'tr:na',
    TrainingNewPlayerCancel: 'tr:nx',

    ChatPrefix: 'c:v:',
    ChatTogglePrefix: 'c:t:',
    ChatDeletePrefix: 'c:d:',
    ChatDeleteConfirmPrefix: 'c:x:',

    SettingsToggleCleanChat: 'cfg:tc',
    SettingsEditPrefix: 'cfg:e:',
    SettingsAdmins: 'cfg:a',
    SettingsAddAdmin: 'cfg:aa',
    SettingsAddAdminConfirm: 'cfg:aok',
    SettingsRemoveAdmin: 'cfg:ar',
    SettingsRemoveAdminConfirm: 'cfg:rok',
    SettingsTransferOwner: 'cfg:to',
    SettingsTransferOwnerConfirm: 'cfg:tok',
    SettingsRemoveAdminPrefix: 'cfg:ar:',
    SettingsStatus: 'cfg:st',

    Help: 'h',

    ClubRequestList: 'cr:l',
    ClubRequestCreate: 'cr:n',
    ClubRequestConfirm: 'cr:ok',
    ClubRequestEdit: 'cr:e',
    ClubRequestCancel: 'cr:c',
    ClubRequestViewPrefix: 'cr:v:',
    ClubRequestApprovePrefix: 'cr:a:',
    ClubRequestRejectPrefix: 'cr:r:',
    ClubRequestEditPrefix: 'cr:e:',
    ClubRequestCancelPrefix: 'cr:c:',
} as const;
